### ISSUE TITLE
TypeScript error: Could not find a declaration file for module 'three-orbitcontrols'.

### ISSUE THREAD

**Issue by mavrickp** [chrisrzhou/google-globe-trends#1]
Try `npm install @types/three-orbitcontrols` if it exists or add a new declaration (.d.ts) file containing `declare module 'three-orbitcontrols';`  TS7016

    1 | import { useEffect, useRef } from 'react';
    2 | import { AmbientLight, Color, PerspectiveCamera, PointLight } from 'three';
  > 3 | import OrbitControls from 'three-orbitcontrols';
      |                           ^

**Comment by chrisrzhou** [comment]
@mavrickp, thanks for reporting this! I'm aware of the issue but haven't had time to get to it.  I'm also fixing up Typescript conventions in `react-globe` (new to Typescript, but loving it).  If this is not blocking, I expect to get this fixed up within the next 1-2 weeks.

Thanks for checking the app out!

**Comment by mavrickp** [comment]
> @mavrickp, thanks for reporting this! I'm aware of the issue but haven't had time to get to it. I'm also fixing up Typescript conventions in `react-globe` (new to Typescript, but loving it). If this is not blocking, I expect to get this fixed up within the next 1-2 weeks.
> 
> Thanks for checking the app out!

Hope this can be fixed soon

**Comment by chrisrzhou** [comment]
Hey @mavrickp, I just pushed updates to this repo since the underlying `react-globe` package has been upgrade from `v3.0.0` to `v5.0.0`.  There's a couple of small changes to the interface so make sure to check out https://react-globe.netlify.app/ for details on how to use the `options` prop.

For the typings for `OrbitControls`, `react-globe@v5.0.0` uses an updated version of `three` for peer dependency, and these include native typings for `three-orbitcontrols`, so you don't have to install these from `@types`.  You should be able to import them directly as in this example:

https://github.com/chrisrzhou/react-globe/blob/main/lib/orbit-controls.js#L1
